### ISSUE TITLE
1.19.2 AE2 Sky Stone Error (Won't break/Ghosting)

### ISSUE THREAD

**Issue by Shybella** [Tourmi/mc-server-side-vein-miner#15]
**Description**

**Steps to Reproduce**
1. Download Direwolf20 1.19.2 using the FTBApp.
2. Add SVMM to the mods folder.
3. Login to a single player world, attempt to break an AE2 meteor made of sky stone 

Log(error): https://pastebin.com/raw/LnxpED4C

**Expected behavior**
This shouldn't be attempting to Veinmine Sky stone, it really shouldn't be done. Having a config option that includes blocks to ignore would be ideal. 

**Versions**
Minecraft version: 1.19.2
Forge version: 40.2.4
Mod version: svmm-1.19.2-1.2.3.0.jar

Thank you for making this mod, it works great! Exactly what I needed!

**Comment by Tourmi** [comment]
Fixed for 1.19.2 in release https://github.com/Tourmi/mc-server-side-vein-miner/releases/tag/1.19.2-1.2.3.2
