### ISSUE TITLE
Command suggestions gone

### ISSUE THREAD

**Issue by Onkel-H** [Tourmi/mc-server-side-vein-miner#22]
After installing this mod i no longer get command suggestions. The commands are still working, but the suggestions are not showing.

I run a dedicated pc just for the server and the client on another pc.
Before installing a mod i take a backup, and just by stopping the server with this mod and starting the backup (saved just before i installed the mod) i was able to get the suggestions again. So clearly this mod does something. (The client was left running in between server change)

Both server and client run on  Forge 1.20.2-48.1.0
Tested mod version:   svmm-1.20.1-1.2.4.0
I also have a few other mods but everything worked fine before.

**Comment by Tourmi** [comment]
I have not been able to reproduce the problem using the 1.20.1-1.2.4.0 version of the mod. I ran the mod on Forge 1.20.1-47.0.1, 1.20.1-47.2.20 and 1.20.2-48.1.0

Could you send a list of your mods, so I can check for incompatibilities?

**Comment by Onkel-H** [comment]
Hi, sorry for late reply. Here is my list of mods when everything worked correctly:

- LuckPerms-Forge-5.4.109
- Pixelmon-1.20.2-9.2.5-universal
- Corpse-1.20.2-1.0.9
- JEI-1.20.2-forge-16.0.0.28  (just enough items, if unclear)
- Journeymap-1.20.2-5.9.18-forge
- Uncrafted-1.20.x-(v.4.2.1)
- Worldedit-mod-7.2.17

Can also confirm that being  /op or having command.* set true will influence the issue. With the extra permission levels it will make suggestions go away, without it the suggestions is back on.
I can deop / remove commands permission and the suggestions pop right back up in same session.
If i add the command.* then the suggestions are only there until i rejoin server.

**Comment by GeniusLocEye** [comment]
This is also happening with me. Installing the mod on the server, if it is not on the client, it won't give me command suggestions.
