### ISSUE TITLE
Version 1.20.1 seems to give me the prompt "invalid player data" when creating/joining a premade singleplayer world.

### ISSUE THREAD

**Issue by TheCuteCultist** [Tourmi/mc-server-side-vein-miner#24]
**Description**
When creating a world, after its done loading the start up process when creating a world, it shows "Invalid player data" prompt.
Including when trying to join the single player world just made.

**Steps to Reproduce**
1. Open minecraft
2. Create new singleplayer world
3. After new world is done loading it will give the prompt "Invalid player data"
 Alternatively
1. Join a pre-existing singleplayer world
2. Gives same "Invalid Player Data" Prompt

**Expected behavior**
When a world is created, it shows the prompt "Invalid player data" any time you make/join a singleplayer world. If you click back to sever list, it takes you to the multiplayer server list.

**Screenshots**
![javaw_BstTziGx05](https://github.com/Tourmi/mc-server-side-vein-miner/assets/158857691/cee4913e-b7c6-4614-89f8-808322c8244a)

**Versions**
Minecraft version: 1.20.1
Forge version: 47.2.0
Mod version: 1.2.4.0 (i think thats right T_T)

**Comment by Tourmi** [comment]
Cannot reproduce the issue
