### ISSUE TITLE
[1.20.1] Mod crashes dedicated server on launch.

### ISSUE THREAD

**Issue by Acenthus** [Tourmi/mc-server-side-vein-miner#38]
## Description
Attempting to run the dedicated forge server with svmm results in a crash.

## Steps to Reproduce
1. Put the mod into the mods folder of a dedicated server
2. Run the server

## Expected behavior
The server should boot as normal with the mod on.

## Versions
| Component         | Version |
| ----------------: | :------ |
| Minecraft version | 1.20.1 |
| Forge version     | 47.3.1 |
| Mod version       | 1.3.0.2 |

**Comment by Tourmi** [comment]
I can't fix this issue today, I recommend downgrading to 1.2.4.5 since it'll have the same features for now

**Comment by Tourmi** [comment]
Fixed in 1.3.0.3
